version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ecoshub/jin
    environment:
      TEST_RESULTS: /tmp/test-results 
    docker:
    - image: circleci/golang:1.9
    steps:
    - run: curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    - run: sudo apt-get install -y nodejs
    - checkout
    - run: go get -v -t -d
    - run: go test -v